// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen8_screen_init(void)
{
    ui_Screen8 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image25 = lv_image_create(ui_Screen8);
    lv_image_set_src(ui_Image25, &ui_img_bg_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 571
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label61 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, 2);
    lv_obj_set_y(ui_Label61, -146);
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "充电枪已解锁, 请拔出充电枪");
    lv_obj_set_style_text_color(ui_Label61, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label61, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button26 = lv_button_create(ui_Screen8);
    lv_obj_set_width(ui_Button26, 191);
    lv_obj_set_height(ui_Button26, 50);
    lv_obj_set_x(ui_Button26, 0);
    lv_obj_set_y(ui_Button26, 41);
    lv_obj_set_align(ui_Button26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button26, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label62 = lv_label_create(ui_Button26);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label62, "我已拔出");
    lv_obj_set_style_text_font(ui_Label62, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button26, ui_event_Button26, LV_EVENT_ALL, NULL);

}
