// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image1, &ui_img_bg_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);  /// 800
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT); /// 571
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image2 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image2, &ui_img_tesla_car_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);  /// 1050
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT); /// 694
    lv_obj_set_x(ui_Image2, 17);
    lv_obj_set_y(ui_Image2, 9);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image2, 120);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label1, -1);
    lv_obj_set_y(ui_Label1, -195);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "欢迎使用共享充电桩");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 213);
    lv_obj_set_height(ui_Button2, 74);
    lv_obj_set_x(ui_Button2, 272);
    lv_obj_set_y(ui_Button2, 171);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_radius(ui_Button2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_bg_image_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_shadow_width(ui_Button2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "开始充电");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image15, &ui_img_left_side_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);  /// 131
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT); /// 800
    lv_obj_set_x(ui_Image15, -350);
    lv_obj_set_y(ui_Image15, -27);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image13 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image13, &ui_img_pricing_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);  /// 31
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT); /// 28
    lv_obj_set_x(ui_Image13, -345);
    lv_obj_set_y(ui_Image13, -130);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image13, 400);

    ui_Label45 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label45, -344);
    lv_obj_set_y(ui_Label45, -96);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "pricing");
    lv_obj_set_style_text_color(ui_Label45, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, lv_pct(100));
    lv_obj_set_height(ui_Container7, lv_pct(100));
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container7, LV_OBJ_FLAG_HIDDEN);        /// Flags
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Container7, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container7, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label50, 0);
    lv_obj_set_y(ui_Label50, -31);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "价格:快充1.8元,慢充1.2元");
    lv_obj_set_style_text_color(ui_Label50, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label50, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button23 = lv_button_create(ui_Container7);
    lv_obj_set_width(ui_Button23, 100);
    lv_obj_set_height(ui_Button23, 50);
    lv_obj_set_x(ui_Button23, 0);
    lv_obj_set_y(ui_Button23, 72);
    lv_obj_set_align(ui_Button23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button23, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_Button23, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_radius(ui_Button23, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Button23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);
    ui_object_set_themeable_style_property(ui_Button23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_shadow_width(ui_Button23, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button23, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button23, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button23, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button23, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button23, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_Button23);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "好的");
    lv_obj_set_style_text_font(ui_Label51, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image13, ui_event_Image13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button23, ui_event_Button23, LV_EVENT_ALL, NULL);
}
