// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen10_screen_init(void)
{
    ui_Screen10 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image30 = lv_image_create(ui_Screen10);
    lv_image_set_src(ui_Image30, &ui_img_bg_png);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 571
    lv_obj_set_align(ui_Image30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button34 = lv_button_create(ui_Screen10);
    lv_obj_set_width(ui_Button34, 64);
    lv_obj_set_height(ui_Button34, 50);
    lv_obj_set_x(ui_Button34, -361);
    lv_obj_set_y(ui_Button34, -213);
    lv_obj_set_align(ui_Button34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button34, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button34, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Button34, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button34, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);
    ui_object_set_themeable_style_property(ui_Button34, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button34, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_shadow_width(ui_Button34, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button34, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button34, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button34, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button34, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button34, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image33 = lv_image_create(ui_Button34);
    lv_image_set_src(ui_Image33, &ui_img_home_png);
    lv_obj_set_width(ui_Image33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image33, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image33, 100);

    ui_TextArea6 = lv_textarea_create(ui_Screen10);
    lv_obj_set_width(ui_TextArea6, 316);
    lv_obj_set_height(ui_TextArea6, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea6, 0);
    lv_obj_set_y(ui_TextArea6, -191);
    lv_obj_set_align(ui_TextArea6, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea6, "account...");
    lv_textarea_set_one_line(ui_TextArea6, true);



    ui_TextArea7 = lv_textarea_create(ui_Screen10);
    lv_obj_set_width(ui_TextArea7, 316);
    lv_obj_set_height(ui_TextArea7, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea7, 0);
    lv_obj_set_y(ui_TextArea7, -91);
    lv_obj_set_align(ui_TextArea7, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea7, "Placeholder...");
    lv_textarea_set_one_line(ui_TextArea7, true);
    lv_textarea_set_password_mode(ui_TextArea7, true);



    ui_Label64 = lv_label_create(ui_Screen10);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label64, -220);
    lv_obj_set_y(ui_Label64, -188);
    lv_obj_set_align(ui_Label64, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label64, "账号:");
    lv_obj_set_style_text_color(ui_Label64, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label64, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label64, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label65 = lv_label_create(ui_Screen10);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, -220);
    lv_obj_set_y(ui_Label65, -90);
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, "密码:");
    lv_obj_set_style_text_color(ui_Label65, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label65, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label65, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button36 = lv_button_create(ui_Screen10);
    lv_obj_set_width(ui_Button36, 213);
    lv_obj_set_height(ui_Button36, 74);
    lv_obj_set_x(ui_Button36, 272);
    lv_obj_set_y(ui_Button36, 171);
    lv_obj_set_align(ui_Button36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button36, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button36, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button36, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_bg_grad_dir(ui_Button36, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Button36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Button36, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button36, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_shadow_width(ui_Button36, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button36, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button36, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button36, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button36, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button36, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label67 = lv_label_create(ui_Button36);
    lv_obj_set_width(ui_Label67, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label67, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label67, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label67, "下一步");
    lv_obj_set_style_text_font(ui_Label67, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image34 = lv_image_create(ui_Button36);
    lv_image_set_src(ui_Image34, &ui_img_nextt_png);
    lv_obj_set_width(ui_Image34, 198);
    lv_obj_set_height(ui_Image34, 78);
    lv_obj_set_x(ui_Image34, -6);
    lv_obj_set_y(ui_Image34, 0);
    lv_obj_set_align(ui_Image34, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image34, 100);

    ui_Keyboard4 = lv_keyboard_create(ui_Screen10);
    lv_keyboard_set_mode(ui_Keyboard4, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard4, lv_pct(100));
    lv_obj_set_height(ui_Keyboard4, lv_pct(50));
    lv_obj_set_x(ui_Keyboard4, 0);
    lv_obj_set_y(ui_Keyboard4, 120);
    lv_obj_set_align(ui_Keyboard4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_Button34, ui_event_Button34, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea6, ui_event_TextArea6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea7, ui_event_TextArea7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button36, ui_event_Button36, LV_EVENT_ALL, NULL);

}
