// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"
#include <stdio.h>
#include "../../src/charging_system.h"
#include "../../src/user_auth.h"

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image12 = lv_image_create(ui_Screen7);
    lv_image_set_src(ui_Image12, &ui_img_bg_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);  /// 800
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT); /// 571
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label44 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label44, 0);
    lv_obj_set_y(ui_Label44, -213);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "结算");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label46, 0);
    lv_obj_set_y(ui_Label46, -150);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "充电时长: 00:00:00");
    lv_obj_set_style_text_color(ui_Label46, lv_color_hex(0xFFC93B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label46, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label47, 0);
    lv_obj_set_y(ui_Label47, -84);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "已充入: 00.0kwH");
    lv_obj_set_style_text_color(ui_Label47, lv_color_hex(0xFF1ED1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label47, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label48 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label48, 0);
    lv_obj_set_y(ui_Label48, 100);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "电费:00.00");
    lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0x00D7FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label48, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label49, 0);
    lv_obj_set_y(ui_Label49, -8);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "平均功率:000.0kw");
    lv_obj_set_style_text_color(ui_Label49, lv_color_hex(0x29FE5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label49, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button25 = lv_button_create(ui_Screen7);
    lv_obj_set_width(ui_Button25, 345);
    lv_obj_set_height(ui_Button25, 74);
    lv_obj_set_x(ui_Button25, 223);
    lv_obj_set_y(ui_Button25, 176);
    lv_obj_set_align(ui_Button25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    ui_object_set_themeable_style_property(ui_Button25, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button25, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_bg_grad_dir(ui_Button25, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Button25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Button25, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button25, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_shadow_width(ui_Button25, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button25, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button25, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button25, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button25, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button25, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Button25);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "请选择支付方式");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image20 = lv_image_create(ui_Button25);
    lv_image_set_src(ui_Image20, &ui_img_nextt_png);
    lv_obj_set_width(ui_Image20, 407);
    lv_obj_set_height(ui_Image20, 57);
    lv_obj_set_x(ui_Image20, 52);
    lv_obj_set_y(ui_Image20, -1);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image20, 100);

    ui_Container8 = lv_obj_create(ui_Screen7);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, lv_pct(100));
    lv_obj_set_height(ui_Container8, lv_pct(100));
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container8, LV_OBJ_FLAG_HIDDEN);        /// Flags
    lv_obj_remove_flag(ui_Container8, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Container8, lv_color_hex(0x696969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container8, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image19 = lv_image_create(ui_Container8);
    lv_image_set_src(ui_Image19, &ui_img_alipay_icon_png);
    lv_obj_set_width(ui_Image19, lv_pct(13));
    lv_obj_set_height(ui_Image19, lv_pct(20));
    lv_obj_set_x(ui_Image19, lv_pct(-30));
    lv_obj_set_y(ui_Image19, lv_pct(0));
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image19, 43);

    ui_Image21 = lv_image_create(ui_Container8);
    lv_image_set_src(ui_Image21, &ui_img_wechat_payment_icon_png);
    lv_obj_set_width(ui_Image21, 93);
    lv_obj_set_height(ui_Image21, 102);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image21, 18);

    ui_Image22 = lv_image_create(ui_Container8);
    lv_image_set_src(ui_Image22, &ui_img_wallet_icon_png);
    lv_obj_set_width(ui_Image22, 104);
    lv_obj_set_height(ui_Image22, 103);
    lv_obj_set_y(ui_Image22, 0);
    lv_obj_set_x(ui_Image22, lv_pct(30));
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image22, 260);

    ui_Container9 = lv_obj_create(ui_Screen7);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, lv_pct(100));
    lv_obj_set_height(ui_Container9, lv_pct(100));
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container9, LV_OBJ_FLAG_HIDDEN);        /// Flags
    lv_obj_remove_flag(ui_Container9, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Container9, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container9, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23 = lv_image_create(ui_Container9);
    lv_image_set_src(ui_Image23, &ui_img_qr_code1_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image23, 5);
    lv_obj_set_y(ui_Image23, 60);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label20 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, -188);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "请使用微信支付");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x00FF1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button28 = lv_button_create(ui_Container9);
    lv_obj_set_width(ui_Button28, 100);
    lv_obj_set_height(ui_Button28, 50);
    lv_obj_set_x(ui_Button28, 250);
    lv_obj_set_y(ui_Button28, 96);
    lv_obj_set_align(ui_Button28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button28, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_Button28, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_radius(ui_Button28, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button28, lv_color_hex(0xDF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button28, lv_color_hex(0xE10505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button28, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button28, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button28, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button28, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button28, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button28, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label56 = lv_label_create(ui_Button28);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "返回");
    lv_obj_set_style_text_color(ui_Label56, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label56, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label56, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button29 = lv_button_create(ui_Container9);
    lv_obj_set_width(ui_Button29, 213);
    lv_obj_set_height(ui_Button29, 74);
    lv_obj_set_x(ui_Button29, 272);
    lv_obj_set_y(ui_Button29, 171);
    lv_obj_set_align(ui_Button29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button29, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_Button29, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    ui_object_set_themeable_style_property(ui_Button29, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button29, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_bg_grad_dir(ui_Button29, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Button29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Button29, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button29, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_shadow_width(ui_Button29, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button29, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button29, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button29, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button29, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button29, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label57 = lv_label_create(ui_Button29);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label57, "下一步");
    lv_obj_set_style_text_font(ui_Label57, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image26 = lv_image_create(ui_Button29);
    lv_image_set_src(ui_Image26, &ui_img_nextt_png);
    lv_obj_set_width(ui_Image26, 198);
    lv_obj_set_height(ui_Image26, 78);
    lv_obj_set_x(ui_Image26, -6);
    lv_obj_set_y(ui_Image26, 0);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image26, 100);

    ui_Container11 = lv_obj_create(ui_Screen7);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, lv_pct(100));
    lv_obj_set_height(ui_Container11, lv_pct(100));
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container11, LV_OBJ_FLAG_HIDDEN);        /// Flags
    lv_obj_remove_flag(ui_Container11, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container11, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image24 = lv_image_create(ui_Container11);
    lv_image_set_src(ui_Image24, &ui_img_qr_code2_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image24, 4);
    lv_obj_set_y(ui_Image24, 54);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image24, 215);

    ui_Label52 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label52, 0);
    lv_obj_set_y(ui_Label52, -188);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "请使用支付宝支付");
    lv_obj_set_style_text_color(ui_Label52, lv_color_hex(0x0100FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label52, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label52, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button27 = lv_button_create(ui_Container11);
    lv_obj_set_width(ui_Button27, 100);
    lv_obj_set_height(ui_Button27, 50);
    lv_obj_set_x(ui_Button27, 250);
    lv_obj_set_y(ui_Button27, 96);
    lv_obj_set_align(ui_Button27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button27, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_Button27, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_radius(ui_Button27, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button27, lv_color_hex(0xDF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button27, lv_color_hex(0xE10505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button27, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button27, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button27, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button27, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button27, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button27, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_Button27);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "返回");
    lv_obj_set_style_text_color(ui_Label55, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label55, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button30 = lv_button_create(ui_Container11);
    lv_obj_set_width(ui_Button30, 213);
    lv_obj_set_height(ui_Button30, 74);
    lv_obj_set_x(ui_Button30, 272);
    lv_obj_set_y(ui_Button30, 171);
    lv_obj_set_align(ui_Button30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button30, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_Button30, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    ui_object_set_themeable_style_property(ui_Button30, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button30, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_bg_grad_dir(ui_Button30, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Button30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Button30, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button30, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_shadow_width(ui_Button30, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button30, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button30, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button30, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button30, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button30, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_Button30);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "下一步");
    lv_obj_set_style_text_font(ui_Label58, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image27 = lv_image_create(ui_Button30);
    lv_image_set_src(ui_Image27, &ui_img_nextt_png);
    lv_obj_set_width(ui_Image27, 198);
    lv_obj_set_height(ui_Image27, 78);
    lv_obj_set_x(ui_Image27, -6);
    lv_obj_set_y(ui_Image27, 0);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image27, 100);

    ui_Container12 = lv_obj_create(ui_Screen7);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, lv_pct(100));
    lv_obj_set_height(ui_Container12, lv_pct(100));
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container12, LV_OBJ_FLAG_HIDDEN);        /// Flags
    lv_obj_remove_flag(ui_Container12, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Container12, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container12, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label59 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, "扣款成功! \n本次消费:00.0元\n剩余余额:00.0元");
    lv_obj_set_style_text_color(ui_Label59, lv_color_hex(0x00FF09), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label59, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button31 = lv_button_create(ui_Container12);
    lv_obj_set_width(ui_Button31, 213);
    lv_obj_set_height(ui_Button31, 74);
    lv_obj_set_x(ui_Button31, 272);
    lv_obj_set_y(ui_Button31, 171);
    lv_obj_set_align(ui_Button31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button31, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_Button31, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    ui_object_set_themeable_style_property(ui_Button31, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button31, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_bg_grad_dir(ui_Button31, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Button31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Button31, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button31, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_shadow_width(ui_Button31, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button31, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button31, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button31, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button31, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button31, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60 = lv_label_create(ui_Button31);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60, "下一步");
    lv_obj_set_style_text_font(ui_Label60, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image28 = lv_image_create(ui_Button31);
    lv_image_set_src(ui_Image28, &ui_img_nextt_png);
    lv_obj_set_width(ui_Image28, 198);
    lv_obj_set_height(ui_Image28, 78);
    lv_obj_set_x(ui_Image28, -6);
    lv_obj_set_y(ui_Image28, 0);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image28, 100);

    ui_Container10 = lv_obj_create(ui_Screen7);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, lv_pct(100));
    lv_obj_set_height(ui_Container10, lv_pct(100));
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container10, LV_OBJ_FLAG_HIDDEN);        /// Flags
    lv_obj_remove_flag(ui_Container10, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Container10, lv_color_hex(0x838383), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container10, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label53, 0);
    lv_obj_set_y(ui_Label53, -100);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "余额不足!请使用其他支付方式!");
    lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label53, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button24 = lv_button_create(ui_Container10);
    lv_obj_set_width(ui_Button24, 100);
    lv_obj_set_height(ui_Button24, 50);
    lv_obj_set_x(ui_Button24, 0);
    lv_obj_set_y(ui_Button24, 96);
    lv_obj_set_align(ui_Button24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button24, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_Button24, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_radius(ui_Button24, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button24, lv_color_hex(0xDF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button24, lv_color_hex(0xE10505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button24, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button24, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button24, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button24, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button24, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button24, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_Button24);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "返回");
    lv_obj_set_style_text_color(ui_Label54, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label54, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label54, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button25, ui_event_Button25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image19, ui_event_Image19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image21, ui_event_Image21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image22, ui_event_Image22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button28, ui_event_Button28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button29, ui_event_Button29, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button27, ui_event_Button27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button30, ui_event_Button30, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button31, ui_event_Button31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button24, ui_event_Button24, LV_EVENT_ALL, NULL);

    // 初始化时更新结算信息
    update_billing_summary();
}

// 更新结算界面的信息显示
void update_billing_summary(void)
{
    // 获取充电数据
    const charging_data_t * charging_data = get_charging_data();

    // 更新充电时长
    char duration_buffer[64];
    get_charging_duration_string(duration_buffer, sizeof(duration_buffer));
    char duration_text[128];
    snprintf(duration_text, sizeof(duration_text), "充电时长: %s", duration_buffer);
    lv_label_set_text(ui_Label46, duration_text);

    // 更新已充入电量
    char energy_text[64];
    snprintf(energy_text, sizeof(energy_text), "已充入: %.1fkwH", charging_data->energy_charged);
    lv_label_set_text(ui_Label47, energy_text);

    // 更新平均功率
    double avg_power = 0.0;
    if(charging_data->current_time > charging_data->start_time && charging_data->start_time > 0) {
        time_t duration = charging_data->current_time - charging_data->start_time;
        if(duration > 0) {
            avg_power = charging_data->energy_charged / (duration / 3600.0); // 小时
        }
    }
    char power_text[64];
    snprintf(power_text, sizeof(power_text), "平均功率:%.1fkw", avg_power);
    lv_label_set_text(ui_Label49, power_text);

    // 更新电费
    double total_cost = calculate_charging_cost();
    char cost_text[64];
    snprintf(cost_text, sizeof(cost_text), "电费:%.2f元", total_cost);
    lv_label_set_text(ui_Label48, cost_text);

    printf("[DEBUG] Billing Summary - Duration: %s, Energy: %.1fkWh, Avg Power: %.1fkW, Cost: %.2f\n", duration_buffer,
           charging_data->energy_charged, avg_power, total_cost);
}
