// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen9_screen_init(void)
{
    ui_Screen9 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image29 = lv_image_create(ui_Screen9);
    lv_image_set_src(ui_Image29, &ui_img_bg_png);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 571
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label63 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label63, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label63, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label63, 0);
    lv_obj_set_y(ui_Label63, -73);
    lv_obj_set_align(ui_Label63, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label63, "感谢您的使用!");
    lv_obj_set_style_text_color(ui_Label63, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label63, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label63, &ui_font_chinese48title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button33 = lv_button_create(ui_Screen9);
    lv_obj_set_width(ui_Button33, 231);
    lv_obj_set_height(ui_Button33, 88);
    lv_obj_set_x(ui_Button33, 0);
    lv_obj_set_y(ui_Button33, 65);
    lv_obj_set_align(ui_Button33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button33, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Button33, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button33, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);
    ui_object_set_themeable_style_property(ui_Button33, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button33, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color2);
    lv_obj_set_style_shadow_width(ui_Button33, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button33, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button33, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button33, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button33, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button33, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image31 = lv_image_create(ui_Button33);
    lv_image_set_src(ui_Image31, &ui_img_home_png);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image31, 100);

    lv_obj_add_event_cb(ui_Button33, ui_event_Button33, LV_EVENT_ALL, NULL);

}
