// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Screen1 主页面
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e); // 开始充电的按钮
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image15;
void ui_event_Image13(lv_event_t * e);
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label50;
void ui_event_Button23(lv_event_t * e); // 主界面价格的返回
extern lv_obj_t * ui_Button23;
extern lv_obj_t * ui_Label51;

// SCREEN: ui_Screen2 身份选择
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
// 商家按钮
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image3;
// 用户按钮
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image4;
// home 按钮
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Image14;

// SCREEN: ui_Screen3 顾客账号登陆
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image6;
// 账号文本框
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
// 密码文本框
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
// 没有账号文本框?注册账号
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label8;
// 登陆按钮下一步
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image17;
// home按钮
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label23;
// 密码错误的返回按钮
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Keyboard1;

// SCREEN: ui_Screen4 顾客创建账户
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image7;
void ui_event_TextArea4(lv_event_t * e); // 创建账号文本框密码要11位
extern lv_obj_t * ui_TextArea4;
void ui_event_TextArea5(lv_event_t * e); // 创建密码文本框
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
void ui_event_Button7(lv_event_t * e); // 创建账号返回上一步按钮
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Keyboard3;
void ui_event_Button32(lv_event_t * e); // 注册按钮
extern lv_obj_t * ui_Button32;
extern lv_obj_t * ui_Label66;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label68;
void ui_event_Button37(lv_event_t * e); // 注册成功页面的上一步
extern lv_obj_t * ui_Button37;
extern lv_obj_t * ui_Label69;

// SCREEN: ui_Screen5 用户选择界面
void ui_Screen5_screen_init(void);
void update_balance_display(void); // 更新余额显示函数
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label9;
// 余额查询按钮
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label16;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label17;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
void ui_event_Label18(lv_event_t * e);
extern lv_obj_t * ui_Label18;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label19;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label22;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label24;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label27;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label28;
void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label31;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label30;
void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label34;
void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Label35;

// SCREEN: ui_Screen6 充电界面
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label39;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label43;

// Screen6 charging update function
void update_charging_display(void);

// SCREEN: ui_Screen7 结算界面
void ui_Screen7_screen_init(void);
void update_billing_summary(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Label49;
void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Container8;
void ui_event_Image19(lv_event_t * e);
extern lv_obj_t * ui_Image19;
void ui_event_Image21(lv_event_t * e);
extern lv_obj_t * ui_Image21;
void ui_event_Image22(lv_event_t * e);
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Label20;
void ui_event_Button28(lv_event_t * e);
extern lv_obj_t * ui_Button28;
extern lv_obj_t * ui_Label56;
void ui_event_Button29(lv_event_t * e);
extern lv_obj_t * ui_Button29;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Label52;
void ui_event_Button27(lv_event_t * e);
extern lv_obj_t * ui_Button27;
extern lv_obj_t * ui_Label55;
void ui_event_Button30(lv_event_t * e);
extern lv_obj_t * ui_Button30;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Image27;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Label59;
void ui_event_Button31(lv_event_t * e);
extern lv_obj_t * ui_Button31;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Image28;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label53;
void ui_event_Button24(lv_event_t * e);
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_Label54;

// SCREEN: ui_Screen8 充电枪解锁界面
void ui_Screen8_screen_init(void);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Label61;
void ui_event_Button26(lv_event_t * e);
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Label62;

// SCREEN: ui_Screen9 感谢界面
void ui_Screen9_screen_init(void);
extern lv_obj_t * ui_Screen9;
extern lv_obj_t * ui_Image29;
extern lv_obj_t * ui_Label63;
void ui_event_Button33(lv_event_t * e);
extern lv_obj_t * ui_Button33;
extern lv_obj_t * ui_Image31;

// SCREEN: ui_Screen10 商家登陆界面
void ui_Screen10_screen_init(void);
extern lv_obj_t * ui_Screen10;
extern lv_obj_t * ui_Image30;
void ui_event_Button34(lv_event_t * e);
extern lv_obj_t * ui_Button34;
extern lv_obj_t * ui_Image33;
void ui_event_TextArea6(lv_event_t * e);
extern lv_obj_t * ui_TextArea6;
void ui_event_TextArea7(lv_event_t * e);
extern lv_obj_t * ui_TextArea7;
extern lv_obj_t * ui_Label64;
extern lv_obj_t * ui_Label65;
void ui_event_Button36(lv_event_t * e);
extern lv_obj_t * ui_Button36;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_Image34;
extern lv_obj_t * ui_Keyboard4;

// SCREEN: ui_Screen11 请在控制台操作界面
void ui_Screen11_screen_init(void);
void ui_Screen11_cleanup(void);
extern lv_obj_t * ui_Screen11;
extern lv_obj_t * ui_Image32;
extern lv_obj_t * ui_Label70;
void ui_event_Button38(lv_event_t * e);
extern lv_obj_t * ui_Button38;
extern lv_obj_t * ui_Image36;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_bg_png);                  // assets/bg.png
LV_IMG_DECLARE(ui_img_tesla_car_png);           // assets/tesla_car.png
LV_IMG_DECLARE(ui_img_left_side_png);           // assets/left_side.png
LV_IMG_DECLARE(ui_img_pricing_png);             // assets/pricing.png
LV_IMG_DECLARE(ui_img_business_png);            // assets/business.png
LV_IMG_DECLARE(ui_img_customer_png);            // assets/customer.png
LV_IMG_DECLARE(ui_img_home_png);                // assets/home.png
LV_IMG_DECLARE(ui_img_nextt_png);               // assets/nextt.png
LV_IMG_DECLARE(ui_img_qrcode_png);              // assets/qrcode.png
LV_IMG_DECLARE(ui_img_alipay_icon_png);         // assets/alipay_icon.png
LV_IMG_DECLARE(ui_img_wechat_payment_icon_png); // assets/wechat_payment_icon.png
LV_IMG_DECLARE(ui_img_wallet_icon_png);         // assets/wallet_icon.png
LV_IMG_DECLARE(ui_img_qr_code1_png);            // assets/qr_code1.png
LV_IMG_DECLARE(ui_img_qr_code2_png);            // assets/qr_code2.png
LV_IMG_DECLARE(ui_img_bg1_png);                 // assets/bg1.png
LV_IMG_DECLARE(ui_img_bg2_png);                 // assets/bg2.png
LV_IMG_DECLARE(ui_img_bg3_png);                 // assets/bg3.png
LV_IMG_DECLARE(ui_img_bg4_png);                 // assets/bg4.png
LV_IMG_DECLARE(ui_img_s1_png);                  // assets/s1.png
LV_IMG_DECLARE(ui_img_s2_png);                  // assets/s2.png
LV_IMG_DECLARE(ui_img_s3_png);                  // assets/s3.png
LV_IMG_DECLARE(ui_img_s4_png);                  // assets/s4.png
LV_IMG_DECLARE(ui_img_s5_png);                  // assets/s5.png
LV_IMG_DECLARE(ui_img_s6_png);                  // assets/s6.png
LV_IMG_DECLARE(ui_img_s7_png);                  // assets/s7.png
LV_IMG_DECLARE(ui_img_s8_png);                  // assets/s8.png
LV_IMG_DECLARE(ui_img_s9_png);                  // assets/s9.png
LV_IMG_DECLARE(ui_img_slider_bg1_png);          // assets/slider_bg1.png
LV_IMG_DECLARE(ui_img_slider_bg2_png);          // assets/slider_bg2.png
LV_IMG_DECLARE(ui_img_slider_bg3_png);          // assets/slider_bg3.png
LV_IMG_DECLARE(ui_img_slider_mask1_png);        // assets/slider_mask1.png
LV_IMG_DECLARE(ui_img_slider_mask2_png);        // assets/slider_mask2.png

LV_FONT_DECLARE(ui_font_chinese48title);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
